version: '3'

services:
    nginx:
       image: nginx:1.15-alpine
       ports:
         - "80:80"
         - "443:443"
       restart: unless-stopped
       volumes:
         - ./data/nginx:/etc/nginx/conf.d:ro
         - ./data/certbot/conf:/etc/letsencrypt:ro
         - ./data/certbot/www:/var/www/certbot:ro
         - ./data/crypto:/var/ssl:ro
       command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
       networks:
         - backend
         - frontend
         - proxy
         - keycloaknet
       extra_hosts:
         - "keycloak:192.168.0.1"

   
    certbot:
       image: certbot/certbot
       restart: unless-stopped
       volumes:
         - ./data/certbot/conf:/etc/letsencrypt:rw
         - ./data/certbot/www:/var/www/certbot:rw
       entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
       networks:
         - proxy

networks:
   frontend:
           external:
                   name: almada234-web
   backend:
           external:
                name: almada234-api
   proxy:
   
   keycloaknet:
           external:
                   name: keycloaknet
